
export const PUBLIC_MEMBER_ONLINE = "PUBLIC_MEMBER_ONLINE"
export const PUBLIC_MEMBER_OFFLINE = "PUBLIC_MEMBER_OFFLINE"
export const SET_FANTASIESEARCHFILTER= "SET_FANTASIESEARCHFILTER";
export const SET_USERSEARCHFILTER= "SET_USERSEARCHFILTER";
export const SET_USERSEARCHTEXT= "SET_USERSEARCHTEXT";
export const SET_USERSEARCHGENRE= "SET_USERSEARCHGENRE";


export const LOAD_MEMBERS = "LOAD_MEMBERS";
export const SET_MEMBER = "SET_MEMBER";
export const SET_MEMBERS = "SET_MEMBERS";
export const ADD_MEMBER = "ADD_MEMBER";
export const DELETE_MEMBER = "DELETE_MEMBER";
export const SET_INBOX = "SET_INBOX";
export const SET_USER = "SET_USER";
export const SET_CONVERSATION = "SET_CONVERSATION";
export const SET_USER_ONLINE = "SET_USER_ONLINE";
export const ADD_MESSAGE = "ADD_MESSAGE";

export const SET_TAGS= "SET_TAGS";


export const SET_CONNECTON = "SET_CONNECTON";